### PR TITLE
xddd Update eval.js

### PR DESCRIPTION
**Pull request by maks1D**
xd

### CODE REVIEW

**Comment by nafcioo** [comment]
:nodebil:

**Comment by marximimus** [comment]
:+1:

**Comment by maks1D** [comment]
:heh:

**Review by efindus — CHANGES_REQUESTED** [review]
Unfortunately, I cannot accept these changes as they would affect the integrity and security of the bot, thus putting its users at risk.

**Comment by efindus** [comment]
OP's response to my change request doesn't really fit within "ok, i'll do something about it" (at least for me). Therefore I'm closing this PR for now.

**Pull request closed without merging**
